### ISSUE TITLE
Inconsistent behavior of the alpha slider in the contrast tab of the Interactive Raycaster window

### ISSUE THREAD

**Issue by Sethur** [bene51/3Dscript#10]
OS: MacOS Mojave
Java: 1.8.0.

Issue: Changing the lower border of the alpha slider in the contrast tab causes instant update of the render preview window, but changing the upper border does bot. For a change of the upper border to be displayed, the render window first has to be focused (i.e. clicked on).

**Comment by bene51** [comment]
Should be fixed in https://github.com/bene51/3Dscript/commit/ff1b425b7e1fd79b4d137b1db084366cc6e3e20d.
The new version is uploaded to the Fiji update site.

**Comment by Sethur** [comment]
Thanks for the quick fix. The plugin is impressive work, even when just considering the fast static rendering. Something that was sorely missing from ImageJ before.
