### ISSUE TITLE
 Create an ImageJ wiki page for 3Dscript

### ISSUE THREAD

**Issue by ctrueden** [bene51/3Dscript#18]
3Dscript was nominated to be featured on the https://fiji.sc front page. But for that, it needs a page on the https://imagej.net wiki.

See discussion at:
https://forum.image.sc/t/which-fiji-plugins-should-be-featured-on-the-front-page/25168/14

**Comment by bene51** [comment]
I've created a page, https://imagej.net/3Dscript.

Is there anything else you need from me?

**Comment by ctrueden** [comment]
Thanks, @bene51!
