### ISSUE TITLE
use in own project

### ISSUE THREAD

**Issue by tischi** [bene51/3Dscript#2]
the project does not have a pom....
can I still somehow use it in own java projects?

**Comment by imagejan** [comment]
It seems like each of the subfolders have their `pom.xml`, but none of the artifacts is currently being deployed to any Maven repository (is it?)...

**Comment by bene51** [comment]
I updated the pom.xml files with a working maven repository (which is so far located on our server):
https://github.com/bene51/3Dscript/blob/964eba129da9c316421c966310f1396470b8da63/3D_Animation/pom.xml#L135-L138

`3D_Animation_Language` is the project that all others are depending on, it contains functionality for parsing and interpreting.

`3D_Animation` is the interactive Fiji plugin, which also includes the OpenCL based renderer.

`3D_Animation_Native` is the native code including OpenCL.

`3D_Animation_IJ3DViewer` is an example adapter that uses the ImageJ 3D Viewer for rendering

`3D_Animation_Povray` is an example adapter that uses POV-Ray for rendering

`3D_Animation_Example_Extension` is a very simple demonstration of how to write an adapter. More details are also described in the manual: [https://bene51.github.io/3Dscript/Manual.pdf](https://bene51.github.io/3Dscript/Manual.pdf)
