### ISSUE TITLE
cut off ROI not being applied to all channels

### ISSUE THREAD

**Issue by apr673** [bene51/3Dscript#22]
OS: MacOS and Windows 7/10

When cutting off the ROI of a dataset with more than 1 colour not all the channels get cropped, even if the option is ticked (usually it fails to crop the 1st channel).
Also, when trying to cutoff single channels, if channel1 is selected, channel 2 will be cut, if channel 2 is selected then channel 3 is cut. For channel 3 it cuts channel 3

**Comment by bene51** [comment]
This is fixed in [https://github.com/bene51/3Dscript/commit/e7d975019d6b283bb63349db84ba3f3419acedfd](https://github.com/bene51/3Dscript/commit/e7d975019d6b283bb63349db84ba3f3419acedfd)

You should get the updated version also through the updater.

Best
