### ISSUE TITLE
Problem with changing the background color

### ISSUE THREAD

**Issue by KarlZhanghao** [bene51/3Dscript#25]
I changed the background color of Fiji as the manual said through Image/Color/Color Picker. However, the background color of 3DScript didn't change at all. My Fiji is updated with version 1.53c. Does anyone know what's wrong? Thanks a lot!

**Comment by bene51** [comment]
Hi Karl,

seems the change didn't make it to the manual, but good to hear that people are reading it ;)

You can change the background color by double-clicking the channel weight slider. There, you can change the channel's color with the ImageJ color picker, but you can also change the background color, as you are used to in Fiji/ImageJ, which will then be used for 3Dscript's background. In case you have more than one channel, you can use any of the sliders for changing the background.

I'll leave this issue open until I updated the manual, so I don't forget.

Best wishes

**Comment by KarlZhanghao** [comment]
Got it, great! Thank you very much, Bene.
