### ISSUE TITLE
Zooming in and out does not return to same position

### ISSUE THREAD

**Issue by habi** [bene51/3Dscript#29]
I would like to generate a movie which involves some zooming in and out of the dataset.
My goal would be that the sample is shown exactly the same way at the beginning of the animation and at the end of the animation, to facilitate showing the movie in a looped way.

I thought that I can achieve this with the script below [1], e.g. zoom in a bit and zoom out again.
````
From frame 0 to frame 1:
- zoom by a factor of 1.5

From frame 2 to frame 3:
- zoom by a factor of 0.75
````
But this doesn't give me the desired result, e.g. frame 0 and frame 3 don't show the sample at the same zoom level.

![Montage](https://user-images.githubusercontent.com/1651235/171836266-9cd968d1-a742-45a3-9878-0691c72edfbb.png)

How can I achieve to show the sample in exactly the same state at the start and end of the movie?

[1]: My 'real' script involves *much* more, but this is boiled down to the bare essentials :)

**Comment by bene51** [comment]
Hi habi,

The default zoom factor is 1, so if you zoom in by a factor of 1.5 (i.e. the ratio is 1.5:1, or 3:2), you'll need to zoom out by the factor of 2:3, or 0.667.

**Comment by habi** [comment]
Aaargh, of course!
Thanks for the pointer, I was confused and thought that the zoom-state is somehow saved.
