### ISSUE TITLE
feature request: manage bookmarks from other plugins

### ISSUE THREAD

**Issue by mutterer** [bene51/3Dscript#5]
It would be nice if BookmarkPanel.java had methods that could be invoked programmatically from third party plugins for the functions exposed in the GUI as loadBookmarks() and saveBookmarks().
Basically loadBookmarks(String bookmarkPath) and saveBookmarks(String bookmarkPath)
Jerome.

**Comment by bene51** [comment]
Implemented in https://github.com/bene51/3Dscript/commit/6c4e389ae5967d5dfc07dd9bf2c2dac7450851da.
The updated version is also available through the Fiji updater.
Best
