### ISSUE TITLE
It made ClearVolume crash in Fiji

### ISSUE THREAD

**Issue by OptoManishK** [bene51/3Dscript#7]
The 3Dscript installation on Fiji went on smoothly and I could open a 3D dataset easily with it. However, when I tried to open the same dataset with ClearVolume (which was there in my Fiji plugin even before 3Dscript was added), it crashed. 

ClearVolume threw an error of authentication 
Device name: 	 ClearCLDevice [mClearCLPlatform=ClearCLPlatform [name=NVIDIA CUDA], name=GeForce GTX 1070 Ti] 
javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsw ..... (cutting the log short)

I shall try to re-install both plugins again. Hoping both of them can work together on the same machine.

(I'm using windows 10 PC and using the plugins with Fiji.)

**Comment by bene51** [comment]
Can you tell me the exact steps to reproduce your issue? I quickly tested by
* Start Fiji and open the T1 Head sample image
* run "Interactive Animation"
* Close the "Interactive Raycaster" window
* Open the image with ClearVolume

without getting any exception. Since there is no google-related code in 3Dscript, I really can't imagine how 3Dscript should cause ClearVolume to throw the exception above.

**Comment by OptoManishK** [comment]
Followed exactly same steps as outlined by you and got same error as originally observed. As such just uninstalling 3Dscript plugin makes ClearVolume run without any issues. I shall perform a fresh installation of Fiji to see if the problem gets solved. May be I should test it out on other OS/PC as well.

Error message:
javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvS
534-5.7.14 9Qk4o8bOLdkX2uwaMsqiFFba.......
534-5.7.14 n8TidyJtPgdaw8Qpon5HK.......
534-5.7.14 WB2ovax1yw.........> Please log
534-5.7.14 in via your web browser and then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 o17sm11310497iob.62 - gsmtp

**Comment by OptoManishK** [comment]
The issue was most likely local to one PC. I could open both 3Dscript and Clearvolume (one after another) on another PC without any problem.
