### ISSUE TITLE
Platform ID error

### ISSUE THREAD

**Issue by comatose-tortoise** [bene51/3Dscript#8]
When trying to open a dataset in 3Dscript, I get the following error in the log: 

`java.lang.RuntimeException: Native exception: Unable to get platform id in H:\fijiplugins\3D_Animation\3D_Animation_Native\Raycaster.cpp (line 73)
	at animation3d.renderer3d.OpenCLRaycaster.initRaycaster8(Native Method)
	at animation3d.renderer3d.OpenCLRaycaster.<init>(OpenCLRaycaster.java:83)
	at animation3d.renderer3d.Renderer3D.<init>(Renderer3D.java:27)
	at animation3d.main.InteractiveRaycaster.run(InteractiveRaycaster.java:130)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
`

I have a Nvidia Titan RTX, running on windows. Is it just that this GPU is not supported or is there something else I could try to make it work?

**Comment by bene51** [comment]
Could you please verify that you have the newest drivers installed, directly from Nvidia? I don't see any reason why this card should not work otherwise. Just for curiosity: Do you have multiple graphics cards?

**Comment by comatose-tortoise** [comment]
Yep, latest drivers, just checked. I only have this card, no integrated GPU or anything like that. What does the error message mean?

**Comment by comatose-tortoise** [comment]
Aldo weird that it mentions ‘H:\fijiplugins\’ since I don’t have an H:

**Comment by bene51** [comment]
It mentions H because that's the location where it was compiled from. That's fine.

Can you go to [https://developer.nvidia.com/opencl](https://developer.nvidia.com/opencl), scroll down to "OpenCL Device Query", download the zip file for your operating system and unpack it. Then locate the executable (it's a bit hidden in the directory structure, on Windows it's in NVIDIA GPU Computing SDK, OpenCL, bin, win64, Release), run it and paste the output on [https://pastebin.com](https://pastebin.com)

**Comment by comatose-tortoise** [comment]
Seems to also have problems identifying "platform"..

https://pastebin.com/vjxWefmt

**Comment by bene51** [comment]
Do you mean something like the 2nd movie here: [https://bene51.github.io/3Dscript/gallery.html](https://bene51.github.io/3Dscript/gallery.html)?

**Comment by comatose-tortoise** [comment]
Yep, found that exemple and copied it. Was just confused initially since it couldn’t be done in the GUI, works fine now, thanks.
