### ISSUE TITLE
In the Interactive Raycaster, dragging the right blue marker onto the left raises exception

### ISSUE THREAD

**Issue by Sethur** [bene51/3Dscript#9]
OS: Mac OS Mojave
Java: 1.8.0

Issue: In the contrast tab of the Interactive Raycaster, setting the alpha row to 0.0 -- 2.0 -- 0.0  by dragging the right blue vertical marker onto the left one causes the plugin to throw an exception (see below). I could replicate this with the T1 head example volume.

`setBoundingBox(0.0, 0.0, 100.0, 5.0)
0.0, 0.0, 100.0, 5.0
0.0, 0.0, 100.0, 5.0
setBoundingBox(-193.0, 0.0, 193.0, 5.0)
-193.0, 0.0, 193.0, 5.0
-193.0, 0.0, 193.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 129.0, 5.0)
0.0, 0.0, 129.0, 5.0
0.0, 0.0, 129.0, 5.0
*** changed default scalebar length to 100.0, pwOut = 1.5000015497207642
javax.swing.JPanel[,0,0,402x736,invalid,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
closing
setBoundingBox(0.0, 0.0, 100.0, 5.0)
0.0, 0.0, 100.0, 5.0
0.0, 0.0, 100.0, 5.0
setBoundingBox(-193.0, 0.0, 193.0, 5.0)
-193.0, 0.0, 193.0, 5.0
-193.0, 0.0, 193.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 129.0, 5.0)
0.0, 0.0, 129.0, 5.0
0.0, 0.0, 129.0, 5.0
*** changed default scalebar length to 100.0, pwOut = 1.5000015497207642
javax.swing.JPanel[,0,0,402x736,invalid,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
closing
setBoundingBox(0.0, 0.0, 100.0, 5.0)
0.0, 0.0, 100.0, 5.0
0.0, 0.0, 100.0, 5.0
setBoundingBox(-193.0, 0.0, 193.0, 5.0)
-193.0, 0.0, 193.0, 5.0
-193.0, 0.0, 193.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 256.0, 5.0)
0.0, 0.0, 256.0, 5.0
0.0, 0.0, 256.0, 5.0
setBoundingBox(0.0, 0.0, 129.0, 5.0)
0.0, 0.0, 129.0, 5.0
0.0, 0.0, 129.0, 5.0
*** changed default scalebar length to 50.0, pwOut = 0.7500007748603821
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = f(66)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = f
*f*
alreadyEntered: f
getCompletionsImpl
getAlreadyEnteredText
Current line = f
*f*
return completions: [From frame ]
getAlreadyEnteredText
Current line = f
*f*
alreadyEntered: f
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 
*From frame *
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 
*From frame *
return completions: [0]
getAlreadyEnteredText
Current line = From frame 
*From frame *
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = r(72)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = r(72)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame r
*From frame r*
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame r
*From frame r*
return completions: [0]
getAlreadyEnteredText
Current line = From frame r
*From frame r*
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = o(6f)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = o(6f)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame ro
*From frame ro*
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame ro
*From frame ro*
return completions: [0]
getAlreadyEnteredText
Current line = From frame ro
*From frame ro*
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = m(6d)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = m(6d)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame rom
*From frame rom*
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame rom
*From frame rom*
return completions: [0]
getAlreadyEnteredText
Current line = From frame rom
*From frame rom*
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = 1(31)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 1(31)
EditorPane: insertUpdate(): lastCharacter = 0(30)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 0(30)
EditorPane: insertUpdate(): lastCharacter =  (20)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 
*From frame 0 *
alreadyEntered: 
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 
*From frame 0 *
return completions: [to frame ]
getAlreadyEnteredText
Current line = From frame 0 
*From frame 0 *
alreadyEntered: 
EditorPane: insertUpdate(): lastCharacter = t(74)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 
*From frame 0 to frame *
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 
*From frame 0 to frame *
return completions: [0]
getAlreadyEnteredText
Current line = From frame 0 to frame 
*From frame 0 to frame *
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = 2(32)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 2(32)
EditorPane: insertUpdate(): lastCharacter = 0(30)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 0(30)
EditorPane: insertUpdate(): lastCharacter = 0(30)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 0(30)
EditorPane: insertUpdate(): lastCharacter =  (20)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 
*From frame 0 to frame 200 *
**
alreadyEntered: 
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 200 
*From frame 0 to frame 200 *
**
return completions: [rotate by , translate , zoom by a factor of , reset transformation , change ]
getAlreadyEnteredText
Current line = From frame 0 to frame 200 
*From frame 0 to frame 200 *
**
alreadyEntered: 
EditorPane: insertUpdate(): lastCharacter = r(72)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 
*From frame 0 to frame 200 rotate by *
*rotate by *
alreadyEntered: EMPTY
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 
*From frame 0 to frame 200 rotate by *
*rotate by *
return completions: [0]
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 
*From frame 0 to frame 200 rotate by *
*rotate by *
alreadyEntered: EMPTY
EditorPane: insertUpdate(): lastCharacter = <(3c)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = >(3e)
EditorPane: insertUpdate(): lastCharacter = 3(33)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 3(33)
EditorPane: insertUpdate(): lastCharacter = 6(36)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 6(36)
EditorPane: insertUpdate(): lastCharacter = 0(30)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character = 0(30)
EditorPane: insertUpdate(): lastCharacter =  (20)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 
*From frame 0 to frame 200 rotate by 360 *
*rotate by 360 *
alreadyEntered: 
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 
*From frame 0 to frame 200 rotate by 360 *
*rotate by 360 *
return completions: [degrees ]
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 
*From frame 0 to frame 200 rotate by 360 *
*rotate by 360 *
alreadyEntered: 
EditorPane: insertUpdate(): lastCharacter = d(64)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees 
*From frame 0 to frame 200 rotate by 360 degrees *
*rotate by 360 degrees *
**
alreadyEntered: 
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees 
*From frame 0 to frame 200 rotate by 360 degrees *
*rotate by 360 degrees *
**
return completions: [horizontally , vertically , around ]
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees 
*From frame 0 to frame 200 rotate by 360 degrees *
*rotate by 360 degrees *
**
alreadyEntered: 
EditorPane: insertUpdate(): lastCharacter = h(68)
AutoActivationListener.insertUpdate
AutoActivationListener.insertUpdate(): timer restarted
AutoActivationListener.actionPerformed()
AutoActivationListener.actionPerformed(): last character =  (20)
AutoActivationListener.actionPerformed(): calling doCompletion()
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees horizontally 
*From frame 0 to frame 200 rotate by 360 degrees horizontally *
*rotate by 360 degrees horizontally *
*horizontally *
**
alreadyEntered: 
getCompletionsImpl
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees horizontally 
*From frame 0 to frame 200 rotate by 360 degrees horizontally *
*rotate by 360 degrees horizontally *
*horizontally *
**
return completions: [(none) , linear , ease-in-out , ease-in , ease-out , ease ]
refreshPopupWindow
getAlreadyEnteredText
Current line = From frame 0 to frame 200 rotate by 360 degrees horizontally 
*From frame 0 to frame 200 rotate by 360 degrees horizontally *
*rotate by 360 degrees horizontally *
*horizontally *
**
alreadyEntered: 
*From frame 0 to frame 200 rotate by 360 degrees horizontally*
*rotate by 360 degrees horizontally*
*horizontally*
**
setBoundingBox(0.0, 0.0, 100.0, 5.0)
0.0, 0.0, 100.0, 5.0
0.0, 0.0, 100.0, 5.0
javax.swing.JPanel[,0,0,402x736,invalid,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,invalid,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
javax.swing.JPanel[,0,0,402x736,layout=java.awt.GridBagLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
	at animation3d.gui.ContrastPanel$DoubleSliderCanvas.paintBuffer(ContrastPanel.java:723)
	at animation3d.gui.DoubleBuffer.paintComponent(DoubleBuffer.java:34)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ArithmeticException: / by zero
	at animation3d.gui.ContrastPanel$DoubleSliderCanvas.paintBuffer(ContrastPanel.java:723)
	at animation3d.gui.DoubleBuffer.paintComponent(DoubleBuffer.java:34)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by bene51** [comment]
Should be fixed in https://github.com/bene51/3Dscript/commit/83beea54b4245217208505009203f251ac4a4476.
The new version is uploaded to the Fiji update site.
